### ISSUE TITLE
potential error

### ISSUE THREAD

**Issue by Ramzess-II** [afiskon/stm32-ili9341#4]
Hello. It seems to me that there is an error in this line in your code. here in theory there should be Y
if(raw_y < ILI9341_TOUCH_MIN_RAW_X) raw_y = ILI9341_TOUCH_MIN_RAW_Y;

**Comment by afiskon** [comment]
You are right, thanks. Fixed: https://github.com/afiskon/stm32-ili9341/commit/dcb183866b44c064004896793a46095a63006f2b
